### ISSUE TITLE
ReferenceError: process is not defined 

### ISSUE THREAD

**Issue by klausbreyer** [rackt/react-redux#184]
Hey, strange error.

I updated to react native 0.14.2 (from 0.13.2) and to react-redux 4.0.0 and

The simulator screen stays white and chrome debug shows me this:
```
index.ios.bundle:712 Error: 
 stack: ReferenceError: process is not defined
    at Object.ReactPerf.measureMethods (http://localhost:8081/index.ios.bundle:56298:4)
    at http://localhost:8081/index.ios.bundle:55576:11
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55338:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55216:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
 line: undefined
 message: process is not defined ReferenceError: process is not defined
    at Object.ReactPerf.measureMethods (http://localhost:8081/index.ios.bundle:56298:4)
    at http://localhost:8081/index.ios.bundle:55576:11
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55338:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:55216:27
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)onError @ index.ios.bundle:712
index.ios.bundle:712 Error: 
 stack: ReferenceError: process is not defined
    at http://localhost:8081/index.ios.bundle:57041:4
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:2839:13
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:2367:23
    at requireImpl (http://localhost:8081/index.ios.bundle:64:13)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at http://localhost:8081/index.ios.bundle:2341:18
 line: undefined
 message: process is not defined ReferenceError: process is not defined(…)onError @ index.ios.bundle:712
debuggerWorker.js:25 Uncaught TypeError: Cannot read property 'flushedQueue' of undefined
index.ios.bundle:712 Error: 
 stack: Error: Requiring module "BatchedBridge" which threw an exception
    at requireImpl (http://localhost:8081/index.ios.bundle:52:7)
    at requireImpl (http://localhost:8081/index.ios.bundle:34:27)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at messageHandlers.executeJSCall (http://localhost:8081/debuggerWorker.js:25:23)
    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:42:5)
 line: undefined
 message: Requiring module "BatchedBridge" which threw an exception Error: Requiring module "BatchedBridge" which threw an exception(…)onError @ index.ios.bundle:712
debuggerWorker.js:25 Uncaught TypeError: Cannot read property 'callFunctionReturnFlushedQueue' of undefined
index.ios.bundle:712 Error: 
 stack: Error: Requiring module "BatchedBridge" which threw an exception
    at requireImpl (http://localhost:8081/index.ios.bundle:52:7)
    at requireImpl (http://localhost:8081/index.ios.bundle:34:27)
    at require (http://localhost:8081/index.ios.bundle:26:8)
    at messageHandlers.executeJSCall (http://localhost:8081/debuggerWorker.js:25:23)
    at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:42:5)
 line: undefined
 message: Requiring module "BatchedBridge" which threw an exception Error: Requiring module "BatchedBridge" which threw an exception(…)onError @ index.ios.bundle:712
debuggerWorker.js:25 Uncaught TypeError: Cannot read property 'callFunctionReturnFlushedQueue' of undefined
27debugger-ui:71 WebSocket connection to 'ws://localhost:8081/debugger-proxy' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

```
{
  "name": "CompletlyNew",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "react-native": "^0.14.2",
       "react-redux": "^4.0.0",
    "redux": "^3.0.3"
  }
}

```
What I did: removed every stain of system node and io.js and reinstalled nvm. My only global installed node module is now react-native-cli.

I prepared a minimal complete example where I just require the Provider. 

```
var Provider = require('react-redux').Provider; 
```
You find it here: https://github.com/klausbreyer/redux-react-debugging-completly-new

Really clueless what to do now.

**Comment by montogeek** [comment]
Oh, I am getting the same error

**Comment by adrianrego** [comment]
Issue also being discussed in: https://github.com/facebook/react-native/issues/4022

**Comment by nodkrot** [comment]
Same issue while upgrading from `"react-native": "^0.14.2"` to ``"react-native": "^0.13.1"`

**Comment by klausbreyer** [comment]
Redux 4 does not support react native.
Vyacheslav Alayev <notifications@github.com> schrieb am Fr., 13. Nov. 2015
um 03:12:

**Comment by gaearon** [comment]
This is definitely not our issue.

First of all, **React Redux 4 does not support React Native yet.** Use React Redux 3.x instead.
We say this in README:

<img width="954" alt="screen shot 2015-11-13 at 14 39 59" src="https://cloud.githubusercontent.com/assets/810438/11145221/70d7dcb4-8a14-11e5-9834-890d5a9bd6f5.png">

and in [4.x release notes](https://github.com/rackt/react-redux/releases/tag/v4.0.0):

<img width="929" alt="screen shot 2015-11-13 at 14 40 41" src="https://cloud.githubusercontent.com/assets/810438/11145225/841d270c-8a14-11e5-8c51-34cbeba705d9.png">

There is nothing we can do here until https://github.com/facebook/react-native/issues/2985 lands. Keep using React Redux 3.x.

**Comment by gaearon** [comment]
As for why you see this specific error, I don't know. We rely on `process.env.NODE_ENV` being polyfilled in React Native which was true for quite some time. If you still have this error even with React Redux 3, it's a React Native issue.

**Comment by psbanka** [comment]
> Use React Redux 3.x instead. We say this in README:
This issue is also occurring with react-redux 3.1.0

**Comment by gaearon** [comment]
Please refer to https://github.com/facebook/react-native/issues/4022. Maybe you have `react` in `node_modules` or need to clear the cache. https://github.com/facebook/react-native/issues/4022#issuecomment-156595431
